# Generated by Django 5.1.4 on 2025-03-14 11:11

import django.db.models.deletion
import django.utils.timezone
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('view_categories', 'Can view categories')], 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='heroimage',
            options={'verbose_name': 'Hero Rasm', 'verbose_name_plural': 'Hero Rasmlar'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'permissions': [('view_inquiries', 'Can view inquiries')], 'verbose_name': "So'rov", 'verbose_name_plural': "So'rovlar"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('view_products', 'Can view products')], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(help_text='Format: +998 (XX) XXX-XX-XX', max_length=18, validators=[products.models.validate_uzbekistan_phone], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text="Narx so'mda kiritiladi", max_digits=20, verbose_name='Narx'),
        ),
    ]
