# Generated by Django 5.0.6 on 2024-12-21 20:31

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=18, validators=[products.models.validate_uzbekistan_phone]),
        ),
    ]
